name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EXPERIMENT_NAME: HeartAttack_tuning
  DATA_PATH: MLProject/heart_preprocessed.csv
  MLFLOW_TRACKING_URI: "https://dagshub.com/dk1781/heart_attack_mlflow.mlflow"
  DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}  
  DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Check environment vars
      - name: Check Env
        run: |
          echo $DATA_PATH

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow dagshub


    # 5. Configure MLflow with Authentication
      - name: Configure MLflow
        run: |
          export MLFLOW_TRACKING_URI="https://dagshub.com/dk1781/heart_attack_mlflow.mlflow"
          export DAGSHUB_TOKEN="${DAGSHUB_TOKEN}"
          export MLFLOW_TRACKING_USERNAME="${DAGSHUB_USERNAME}"
          export MLFLOW_TRACKING_PASSWORD="${DAGSHUB_TOKEN}"
  

      # 5. Run MLflow Project (ini akan menjalankan MLProject/modelling.py via MLproject spec)
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local --run-name rf_run

      # 6. Get latest run_id
      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      # 7. Upload MLflow artifacts (opsional, tapi memenuhi Skilled)
      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts-${{ env.RUN_ID }}
          path: mlruns/0/${{ env.RUN_ID }}

      # 8. Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/randomforest_bestmodel" \
            --name "heart-attack-ci"

      # 9. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 10. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag heart-attack-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:latest
          docker tag heart-attack-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:${{ github.run_id }}

      # 11. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:${{ github.run_id }}
