name: Advanced MLflow CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EXPERIMENT_NAME: HeartAttack_tuning
  DATA_PATH: MLProject/heart_preprocessed.csv
  MLFLOW_TRACKING_URI: "https://dagshub.com/dk1781/heart_attack_mlflow.mlflow"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      # 1. Set up job
      - name: Set up job
        run: echo "Job started"

      # 2. Checkout code
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 3. Set up Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
          cache: 'pip'

      # 4. Check environment variables
      - name: Check Env
        run: |
          echo "EXPERIMENT_NAME=$EXPERIMENT_NAME"
          echo "DATA_PATH=$DATA_PATH"
          echo "MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"

      # 5. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      # 6. Run MLflow project
      - name: Run mflow project
        run: |
          mlflow run MLProject \
            --env-manager=local \
            -P data_path="$DATA_PATH" \
            --no-conda
        env:
          MLFLOW_TRACKING_USERNAME: dk1781
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

      # 7. Get run ID
      - name: Get latest MLflow run_id
        id: get_run
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | awk -F'/' '{print $3}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      # 8. Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install gdown  # Untuk upload ke Google Drive

      # 9. Upload artifacts to GitHub
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts-${{ env.RUN_ID }}
          path: |
            mlruns/0/${{ env.RUN_ID }}/artifacts
            mlruns/0/${{ env.RUN_ID }}/metrics
            mlruns/0/${{ env.RUN_ID }}/params

      # 10. Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ env.RUN_ID }}/randomforest_bestmodel" \
            --name "heart-attack-ci" \
            --enable-mlserver

      # 11. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 12. Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag heart-attack-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:latest
          docker tag heart-attack-ci:latest ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:${{ github.run_id }}

      # 13. Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-attack-ci:${{ github.run_id }}
